config/routes.rb
Rails.application.routes.draw do

  resources :polls do
    resources :questions, shallow: true do
      resources :responses, shallow: true
    end
    get 'fill'
    get 'check_fill'
    post 'preparepoll'
    get 'invitations'
  end

  resources :informajoven

  namespace :api do
    namespace :v1 do
      get '/syncdb' => 'itaca#syncdb'
      get '/recomendaciones' => 'itaca#recomen'
      post '/tratamiento' => 'itaca#tratamiento'
    end
  end
  
  root 'polls#index'

end

app/models/poll.rb
class Poll < ActiveRecord::Base
	has_many :questions
	has_many :invitations
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

	skip_before_filter :verify_authenticity_token, only: [:preparepoll]
	def preparepoll

		poll = Poll.find(params[:poll_id])
		if !poll
			render plain: '{"Error":1003, "Message":"No pollpoll,  requested"}, sort_keys=False)' and return
		end
		invitation_param = params[:invitation];
		if !invitation_param
			render plain: '{"Error":1001, "Message":"No invitation requested"}, sort_keys=False)' and return
		end
		token_param = params[:validation]
		if !token_param
			render plain: '{"Error":1002, "Message":"No validation requested"}, sort_keys=False)' and return
		end
		@invitation = Invitation.new
		@invitation.poll_id = poll.id
		@invitation.invitation = invitation_param
		@invitation.validation_token = token_param

		if @invitation.save
			render plain: '{"Error":0, "Message":"Encuesta preparada para "}, sort_keys=False)' and return
		end
		render plain: '{"Error":1003, "Message":"No data saved"}, sort_keys=False)' and return
	end

	def index
		@polls = Poll.all
	end

	def show
		@poll = Poll.find(params[:id])
	end

	def new
		@poll = Poll.new
	end

	def create
		@poll = Poll.new(poll_params)

		if @poll.save
			redirect_to @poll
		else
			render 'new'
		end
	end

	def edit
		@poll = Poll.find(params[:id])
	end

	def update
		@poll = Poll.find(params[:id])
		if poll.update(poll_params)
			redirect_to @poll
		else
			render 'edit'
		end
	end

	def invitations
		@invitations = Invitation.all
		render json: @invitations
	end

	def destroy
		@poll = Poll.find(params[:id])
		@poll.destroy
		redirect_to polls_path
	end

	def fill
		@poll = Poll.find(params[:poll_id])
		@invitation = Invitation.where(invitation:params[:invitation]).first
		validation = params[:validation]
		if !validation
			render plain: '{"Error":1003, "Message":"Need validation parmas"}, sort_keys=False)' and return
		end
		if !@invitation
			render plain: '{"Error":1003, "Message":"No invitation found"}, sort_keys=False)' and return
		end

		@invitation.validation_mobile = validation
		@invitation.save

	end

	def check_fill
		@invitation = Invitation.where(invitation: params[:invitation]).first
		if !@invitation
			render plain: '{"Error":1003, "Message":"No invitation found"}, sort_keys=False)' and return
		end

		url = 'http://testing.interface.centic.es/checker/validate/externalaction/'+@invitation.invitation+'/?token='+@invitation.validation_token+'&validation='+@invitation.validation_mobile

		response = HTTParty.get(url)
	end

	private
  	def poll_params
    	params.require(:poll).permit(:title, :text)
  	end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.erb
<%= form_for @poll do |f| %>
  <% if @poll.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@poll.errors.count, "error") %> prohibited
      this poll from being saved:</h2>
    <ul>
    <% @poll.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/polls/check_fill.html.erb
<h1> Gracias por haber participado en la encuesta, en breve recibiras tus puntos en la plataforma de gamificación</h1>

app/views/polls/edit.html.erb
<h1>Editar encuesta</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/fill.html.erb
<h1> <%= @poll.title %></h1>
<h2><%= @poll.text %></h2>
<ol>
	<% @poll.questions.each do |question| %>
    <li>
    	<p>
    	<strong>Question:</strong>
    	<%= question.question %>
  		</p>
  		<ul style="list-style: none;">
  			<% question.responses.each do |response| %>
  			<li><input type="radio" name="<%= question.id %>" value="male"/><%= response.text %></li>
  			<% end %>
  		</ul>
    </li>
    <% end %>
</ol>
<a href="/polls/<%= @poll.id %>/check_fill?invitation=<%= @invitation.invitation %>"> Enviar Encuesta</a>

app/views/polls/index.html.erb
<h1>Listing Pollings</h1>
 
 <%= link_to 'New Poll', new_poll_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @polls.each do |poll| %>
    <tr>
      <td><%= poll.title %></td>
      <td><%= poll.text %></td>
      <td><%= link_to 'Show', poll_path(poll) %></td>
      <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
      <td><%= link_to 'Destroy', poll_path(poll), method: :delete, data: { confirm: 'Are you sure?' } %>
    </tr>
  <% end %>
</table>

app/views/polls/new.html.erb
<h1>Crear encuesta</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @poll.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @poll.text %>
</p>

<h2>Questions</h2>
<% @poll.questions.each do |question| %>
  <p>
    <strong>Question:</strong>
    <%= question.question %>
  </p>
  <% question.responses.each do |response| %>
  <p>
    <strong>Response:</strong>
    <%= response.text %>
  </p>
  <% end %>
  <h2>Add a Response:</h2>
	<%= form_for([@poll, question, question.responses.build]) do |f| %>
  	<p>
    	<%= f.label :text %><br>
    	<%= f.text_field :text %>
  	</p>
  	<p>
    	<%= f.label :value %><br>
    	<%= f.text_field :value %>
  	</p>
  	<p>
    <%= f.submit %>
  </p>
<% end %>
<% end %>

<h2>Add a Question:</h2>
<%= form_for([@poll, @poll.questions.build]) do |f| %>
  <p>
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', polls_path %> | <%= link_to 'Edit', edit_poll_path(@poll) %>